<a href="https://colab.research.google.com/github/MuizSarwar/learnML/blob/main/Perceptron_implementation_using_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##**Implementation of Perceptron using Python:-**

In [9]:
#Important libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import joblib

In [29]:
#Perceptron Class:-
class Perceptron:
  #constructor --------------------------------------
  def __init__(self,eta,epochs) -> None:
    self.eta = eta
    self.epochs = epochs
    self.weights = np.random.randn(3) * 1e-4
    print(f"self.weights: {self.weights}")


  #activation method --------------------------------
  def activation_function(self,inputs,weights):
    z = np.dot(inputs,weights)
    return np.where(z > 0,1,0)


  #fit method -----------------------------------------
  def fit(self,X,y):
    self.X,self.y = X,y

    #concatination of  -->  self.X + neg ones array
    X_with_bias = np.c_[self.X,-np.ones((len(self.X),1))]
    print(f"X_with_bias: \n{X_with_bias}")

    for epoch in range(self.epochs):
      print(f"for epoch ------------------------------------------> {epoch}")

      y_hat = self.activation_function(X_with_bias,self.weights)
      print(f"predicted value: \n{y_hat}")

      error = self.y - y_hat
      print(f"error: \n{error}")

      self.weights = self.weights + self.eta * np.dot(X_with_bias.T,error)
      print(f"updated weights: \n{self.weights}")

      print(f"------------------ end epoch {epoch} -----------------------")

  #prediction method -------------------------------------------
  def predict(self,X):
    X_with_bias = np.c_[X, -np.ones((len(self.X), 1))]
    return self.activation_function(X_with_bias,self.weights)


####--> Perceptron on AND operation:

In [27]:
data = {"x1": [0,0,1,1], "x2": [0,1,0,1], "y": [0,0,0,1]}
AND = pd.DataFrame(data)

X = AND.drop('y',axis=1)
y = AND['y']
y.to_frame()

y
0  0
1  0
2  0
3  1

###Create Model & Prediction

In [32]:
perception_model = Perceptron(eta=0.5,epochs=10)
perception_model.fit(X,y)

self.weights: [-4.05146529e-05 -3.11049956e-05  6.83253491e-05]
X_with_bias: 
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
for epoch ------------------------------------------> 0
predicted value: 
[0 0 0 0]
error: 
0    0
1    0
2    0
3    1
Name: y, dtype: int64
updated weights: 
[ 0.49995949  0.4999689  -0.49993167]
------------------ end epoch 0 -----------------------
for epoch ------------------------------------------> 1
predicted value: 
[1 1 1 1]
error: 
0   -1
1   -1
2   -1
3    0
Name: y, dtype: int64
updated weights: 
[-4.05146529e-05 -3.11049956e-05  1.00006833e+00]
------------------ end epoch 1 -----------------------
for epoch ------------------------------------------> 2
predicted value: 
[0 0 0 0]
error: 
0    0
1    0
2    0
3    1
Name: y, dtype: int64
updated weights: 
[0.49995949 0.4999689  0.50006833]
------------------ end epoch 2 -----------------------
for epoch ------------------------------------------> 3
predicted value: 
[0 0 0 1]
error: 
0

### Save and Load the  model

In [33]:
import os

#store the model
dir_ = "Perceptron_model"   #-----> directory name
os.makedirs(dir_,exist_ok=True)   #--------> create the directory
filename = os.path.join(dir_, 'Perceptron_model.model') #----------> create file on the directory
joblib.dump(perception_model,filename)  #--------> save the model on the filename


['Perceptron_model/Perceptron_model.model']

In [34]:
#load the model
loaded_model = joblib.load(filename)